name: Sample
options:
  bundleIdPrefix: test
  deploymentTarget:
    iOS: 13.0
configs:
  Debug: debug
  Release: release
targets:
  Sample:
    type: application
    platform: iOS
    settings:
      base:
        MARKETING_VERSION: 1.1
        CURRENT_PROJECT_VERSION: 1.0
    sources: 
      - path: Sample
